Repository smallrye/smallrye-reactive-messaging, pull requests merged in 2020-12, with the labels that each got.

#884 Support CompletionStage<Void> and Uni<Void> for @Blocking/@Incoming
  documentation/src/main/doc/modules/ROOT/pages/advanced/blocking.adoc
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/AbstractMediator.java
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/MediatorConfigurationSupport.java
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/SubscriberMediator.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/blocking/BlockingSubscriberTest.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/blocking/InvalidBlockingSubscriberShapeTest.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/blocking/beans/IncomingCompletionStageMessageBlockingBean.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/blocking/beans/IncomingCompletionStagePayloadBlockingBean.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/blocking/beans/IncomingUniMessageBlockingBean.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/blocking/beans/IncomingUniPayloadBlockingBean.java
Labels: core, enhancement

#885 Implement getNack for IncomingKafkaRecord
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/IncomingKafkaRecord.java
Labels: bug, kafka

#887 Ignore failure during rebalance
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/i18n/KafkaLogging.java
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/impl/KafkaSource.java
Labels: bug, kafka

#886 Add support for broadcast in the in-memory-connector
  documentation/src/main/doc/modules/ROOT/pages/testing/testing.adoc
  smallrye-reactive-messaging-in-memory/src/main/java/io/smallrye/reactive/messaging/connectors/InMemoryConnector.java
  smallrye-reactive-messaging-in-memory/src/test/java/io/smallrye/reactive/messaging/connectors/InMemoryConnectorWithBroadcastTest.java
Labels: enhancement

#896 Fix GCP Pub/Sub quickstart
  examples/gcp-pubsub-quickstart/pom.xml
  smallrye-reactive-messaging-gcp-pubsub/src/main/java/io/smallrye/reactive/messaging/gcp/pubsub/PubSubManager.java
Labels: bug

#888 Do not attempt retry if an unrecoverable exception is thrown while writing the record.
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/impl/KafkaSink.java
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/base/WeldTestBase.java
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/fault/KafkaNackOnUnrecoverableFailureTest.java
Labels: enhancement, kafka

#908 Fix Emitter overflow tests
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/WeldTestBaseWithoutTails.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/ChannelInjectionTest.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/overflow/BufferOverflowStrategyTest.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/overflow/LegacyEmitterBufferOverflowStrategyTest.java
Labels: bug

#905 Avoid changing the Emitter class from the spec
  api/src/main/java/io/smallrye/reactive/messaging/EmitterBehavior.java
  api/src/main/java/io/smallrye/reactive/messaging/MutinyEmitter.java
  api/src/main/java/org/eclipse/microprofile/reactive/messaging/Emitter.java
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/AbstractEmitter.java
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java
Labels: core

#904 Fix missing getAck / getNack implementation in Message implementations
  smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpMessage.java
  smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/OutgoingAmqpMessage.java
  smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/AmqpBrokerTestBase.java
  smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/AmqpWithConverterTest.java
  smallrye-reactive-messaging-aws-sns/src/main/java/io/smallrye/reactive/messaging/aws/sns/SnsMessage.java
  smallrye-reactive-messaging-camel/src/main/java/io/smallrye/reactive/messaging/camel/CamelMessage.java
  smallrye-reactive-messaging-camel/src/test/java/io/smallrye/reactive/messaging/camel/source/FailureHandlerTest.java
  smallrye-reactive-messaging-gcp-pubsub/src/main/java/io/smallrye/reactive/messaging/gcp/pubsub/PubSubMessage.java
  smallrye-reactive-messaging-http/src/main/java/io/smallrye/reactive/messaging/http/HttpMessage.java
  smallrye-reactive-messaging-jms/src/main/java/io/smallrye/reactive/messaging/jms/IncomingJmsMessage.java
  smallrye-reactive-messaging-mqtt-server/src/main/java/io/smallrye/reactive/messaging/mqtt/server/MqttMessage.java
  smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/ReceivingMqttMessage.java
  smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/SendingMqttMessage.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/converters/ProcessorWithConverterTest.java
  smallrye-reactive-messaging-vertx-eventbus/src/main/java/io/smallrye/reactive/messaging/eventbus/EventBusMessage.java
Labels: amqp, core

#906 Merge the two cloud-events attribute from the Kafka connector
  documentation/src/main/doc/modules/connectors/partials/META-INF/connector/smallrye-kafka-incoming.adoc
  documentation/src/main/doc/modules/connectors/partials/META-INF/connector/smallrye-kafka-outgoing.adoc
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java
Labels: kafka

#910 Do not create Multi when merging / concatenating a single upstream.
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/wiring/Wiring.java
Labels: bug
