Repository smallrye/smallrye-reactive-messaging, pull requests merged in 2020-05, with the labels that each got.

#530 Fix the In Memory connector
  documentation/src/main/doc/modules/ROOT/examples/testing/MyTest.java
  documentation/src/main/doc/modules/ROOT/examples/testing/MyTestSetup.java
  documentation/src/main/doc/modules/ROOT/pages/testing/testing.adoc
  smallrye-reactive-messaging-in-memory/pom.xml
  smallrye-reactive-messaging-in-memory/src/main/java/io/smallrye/reactive/messaging/connectors/InMemoryConnector.java
  smallrye-reactive-messaging-in-memory/src/test/java/io/smallrye/reactive/messaging/connectors/InMemoryConnectorTest.java
Labels: bug

#535 Update getting-started.adoc
  documentation/src/main/doc/modules/ROOT/pages/getting-started.adoc
Labels: bug

#542 Docs: fix annotations in Development Model
  documentation/src/main/doc/modules/ROOT/examples/beans/Chain.java
Labels: bug

#538 Provides a way to configure the default Kafka configuration
  documentation/src/main/doc/modules/kafka/pages/default-configuration.adoc
  documentation/src/main/doc/modules/kafka/pages/kafka.adoc
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/DefaultConfigTest.java
Labels: enhancement

#544 Fix how object encoded to JSON are written into the outbound AMQP message
  documentation/src/main/doc/modules/amqp/pages/inbound.adoc
  documentation/src/main/doc/modules/amqp/pages/outbound.adoc
  smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java
  smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/AmqpSinkTest.java
  smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/ObjectExchangeTest.java
Labels: amqp, bug

#545 MQTT Client and Connection sharing
  documentation/src/main/doc/modules/mqtt/pages/inbound.adoc
  documentation/src/main/doc/modules/mqtt/pages/outbound.adoc
  smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/Clients.java
  smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttConnector.java
  smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttSink.java
  smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttSource.java
  smallrye-reactive-messaging-mqtt/src/test/java/io/smallrye/reactive/messaging/mqtt/ConnectionSharingTest.java
  smallrye-reactive-messaging-mqtt/src/test/java/io/smallrye/reactive/messaging/mqtt/MqttSinkTest.java
  smallrye-reactive-messaging-mqtt/src/test/java/io/smallrye/reactive/messaging/mqtt/MqttSourceTest.java
  smallrye-reactive-messaging-mqtt/src/test/java/io/smallrye/reactive/messaging/mqtt/MultipleTopicsConsumptionTest.java
  smallrye-reactive-messaging-mqtt/src/test/java/io/smallrye/reactive/messaging/mqtt/SecureMqttSourceTest.java
Labels: bug, mqtt

#549 Implement AMQP reconnection
  documentation/src/main/doc/modules/ROOT/pages/emitter/emitter.adoc
  smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpClientHelper.java
  smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java
  smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/ConnectionHolder.java
  smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/AmqpSinkTest.java
  smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/AmqpSourceTest.java
  smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/HeaderPropagationAmqpToAmqpTest.java
  smallrye-reactive-messaging-amqp/src/test/java/io/smallrye/reactive/messaging/amqp/HeaderPropagationAmqpToAppToAmqpTest.java
Labels: amqp, enhancement

#559 Fix #556
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/impl/JsonHelper.java
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/KafkaSourceTest.java
  smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttSink.java
  smallrye-reactive-messaging-mqtt/src/test/java/io/smallrye/reactive/messaging/mqtt/MqttAcknowledgementTest.java
  smallrye-reactive-messaging-mqtt/src/test/java/io/smallrye/reactive/messaging/mqtt/MqttTestBase.java
Labels: bug
