Repository smallrye/smallrye-reactive-messaging, pull requests merged in 2021-02, with the labels that each got.

#971 Improve inheritance support
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/MediatorManager.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/acknowledgement/AsynchronousMessageProcessorAckTest.java
Labels: bug

#970 Fix the default value of the strict configuration property
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/MediatorManager.java
Labels: bug

#978 Update Vert.x to 4.0.2
  pom.xml
Labels: dependencies

#996 refactor health to avoid duplication
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/health/BaseHealth.java
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/health/KafkaSinkReadinessHealth.java
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/health/KafkaSourceReadinessHealth.java
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/base/KafkaTestBase.java
Labels: kafka, to-be-backported

#997 Update SmallRye Metrics to version 3.0.1
  pom.xml
Labels: dependencies

#1000 Update SmallRye Config to version 2.1.0
  documentation/src/main/doc/antora.yml
  pom.xml
Labels: dependencies

#1001 Fix materialization cycle between emitter and mediator methods
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/wiring/Graph.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/wiring/EmitterMethodCycleTest.java
Labels: core, to-be-backported

#1003 Fix subscriber requests
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/SubscriberMediator.java
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/SubscriberWrapper.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/RequestProtocolTest.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/SubscriberShapeTest.java
Labels: bug, core, to-be-backported

#1010 Fix materialization cycle between emitter and mediator methods
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/wiring/Graph.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/wiring/EmitterMethodCycleTest.java
Labels: bug, core

#1011 Fix subscriber requests
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/SubscriberMediator.java
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/SubscriberWrapper.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/RequestProtocolTest.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/SubscriberShapeTest.java
Labels: bug, core

#1004 Update Mutiny to version 0.14.0
  documentation/src/main/doc/antora.yml
  pom.xml
Labels: core, dependencies

#1005 Update Mutiny to 0.14.0 and Vert.x Mutiny API to 2.1.1
  documentation/src/main/doc/antora.yml
  pom.xml
Labels: dependencies

#1012 Bump artemis.version from 2.16.0 to 2.17.0
  pom.xml
  smallrye-reactive-messaging-jms/pom.xml
Labels: dependencies

#1050 Fix key name extraction when the channel contains dot
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/ConfigWithDotsTest.java
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/KafkaSinkTest.java
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/impl/ConnectorConfig.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/merge/MergeTest.java
Labels: backport 3.x, bug, core

#1057 Fix#1053: Use passedConfig over defaultConfig in KafkaConnector
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java
Labels: backport 3.x, bug, kafka

#1059 [3.x] Fix#1053: Use passedConfig over defaultConfig in KafkaConnector (#1057)
  smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java
Labels: backport, bug, kafka

#1067 [3.x] Fix key name extraction when the channel contains dot
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/ConfigWithDotsTest.java
  smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/KafkaSinkTest.java
  smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/impl/ConnectorConfig.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/merge/MergeTest.java
  smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/wiring/EmitterMethodCycleTest.java
Labels: bug, core, kafka
